subscription_id = "******"
tenant_id       = "******"
location        = "eastus"
north_location  = "northeurope"
prefix          = "demo"
vm_username = "adminuser"
vm_password = "@very$trongP@$$word"